#if !canImport(ObjectiveC)
import XCTest

extension TimePointIntervalTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TimePointIntervalTests = [
        ("testAnyTimeOtherThanMaxTimeMinusMaxTime", testAnyTimeOtherThanMaxTimeMinusMaxTime),
        ("testMaxMinusOneTimeMinusMaxTimeInterval", testMaxMinusOneTimeMinusMaxTimeInterval),
        ("testMaxMinusOneTimeMinusMinTimeInterval", testMaxMinusOneTimeMinusMinTimeInterval),
        ("testMaxMinusOneTimePlusMaxTimeInterval", testMaxMinusOneTimePlusMaxTimeInterval),
        ("testMaxMinusOneTimePlusMinTimeInterval", testMaxMinusOneTimePlusMinTimeInterval),
        ("testMaxTimeMinusAnyTimeOtherThanMaxTime", testMaxTimeMinusAnyTimeOtherThanMaxTime),
        ("testMaxTimeMinusMaxTime", testMaxTimeMinusMaxTime),
        ("testMaxTimeMinusMaxTimeInterval", testMaxTimeMinusMaxTimeInterval),
        ("testMaxTimeMinusMinTime", testMaxTimeMinusMinTime),
        ("testMaxTimeMinusMinTimeInterval", testMaxTimeMinusMinTimeInterval),
        ("testMaxTimeMinusNowTime", testMaxTimeMinusNowTime),
        ("testMaxTimePlusMaxTimeInterval", testMaxTimePlusMaxTimeInterval),
        ("testMaxTimePlusMinTimeInterval", testMaxTimePlusMinTimeInterval),
        ("testMinPlusOneTimeMinusMaxTimeInterval", testMinPlusOneTimeMinusMaxTimeInterval),
        ("testMinPlusOneTimeMinusMinTimeInterval", testMinPlusOneTimeMinusMinTimeInterval),
        ("testMinPlusOneTimePlusMaxTimeInterval", testMinPlusOneTimePlusMaxTimeInterval),
        ("testMinPlusOneTimePlusMinTimeInterval", testMinPlusOneTimePlusMinTimeInterval),
        ("testMinTimeMinusMaxTime", testMinTimeMinusMaxTime),
        ("testMinTimeMinusMaxTimeInterval", testMinTimeMinusMaxTimeInterval),
        ("testMinTimeMinusMinTimeInterval", testMinTimeMinusMinTimeInterval),
        ("testMinTimeMinusNowTime", testMinTimeMinusNowTime),
        ("testMinTimePlusMaxTimeInterval", testMinTimePlusMaxTimeInterval),
        ("testMinTimePlusMinTimeInterval", testMinTimePlusMinTimeInterval),
        ("testNowTimeMinusMaxTime", testNowTimeMinusMaxTime),
        ("testNowTimeMinusMinTime", testNowTimeMinusMinTime),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(TimePointIntervalTests.__allTests__TimePointIntervalTests),
    ]
}
#endif
